services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: dev_db
      POSTGRES_PASSWORD: dev_db
      POSTGRES_DB: dev_db
    ports:
      - '5432:5432'
    volumes:
      - .:/usr/postgres_database
